### PR TITLE
Refactoring, adding EventEmitter

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka could you have a look at the README and give me feedback?

**Comment by njam** [comment]
Currently a `Process` is immediately started when the constructor is called. On second thought maybe we should let the user start it manually.
Then this:
```ruby
process_builder = Komenda::ProcessBuilder.new('date')
process_builder.on(:output) { |output| puts "Output: #{output}" }
result = process_builder.start.wait_for
```
Would become more like this:
```ruby
process = Komenda.build('date')
process.on(:output) { |output| puts "Output: #{output}" }
result = process.run
```

wdyt?

**Comment by njam** [comment]
Ok I did the changes.
@tomaszdurka could you review the README?

**Comment by njam** [comment]
Will merge, API discussed with @tomaszdurka

**Comment by tomaszdurka** [comment]
Looks good

**Pull request merged**
